# Generated by Django 5.1.6 on 2025-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='demo',
            field=models.TextField(default=''),
        ),
    ]
