# Generated by Django 5.1.6 on 2025-03-23 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demo_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='demo',
        ),
    ]
