# Generated by Django 5.1.7 on 2025-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='persona',
            field=models.TextField(default=''),
        ),
    ]
