# Generated by Django 5.1.7 on 2025-04-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_agent_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directive',
            name='category',
            field=models.CharField(max_length=32),
        ),
    ]
