# Generated by Django 5.1.7 on 2025-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_directive_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directive',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
