# Generated by Django 5.1.6 on 2025-03-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
