# Generated by Django 5.1.6 on 2025-03-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0002_alter_instruction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instruction',
            options={'ordering': ['group', 'instruction_type', 'name']},
        ),
    ]
