# Generated by Django 5.1.6 on 2025-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0003_alter_instruction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandtemplate',
            name='arguments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
