# Generated by Django 5.1.6 on 2025-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnc', '0004_commandtemplate_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandtemplate',
            name='arguments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
