# Generated by Django 5.1.6 on 2025-03-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainer', '0002_remove_codegenerationdata_rainer_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codegenerationdata',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
