# Generated by Django 5.1.6 on 2025-03-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainer', '0003_codegenerationdata_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codegenerationdata',
            name='version',
        ),
    ]
