# Generated by Django 5.1.6 on 2025-03-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainer', '0004_remove_codegenerationdata_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='codegenerationdata',
            name='drop_number',
            field=models.IntegerField(default=0),
        ),
    ]
