# Generated by Django 5.1.6 on 2025-03-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainer', '0005_codegenerationdata_drop_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codegenerationdata',
            options={'ordering': ('created_at', 'rainer_branch', 'rainer_path')},
        ),
    ]
