# ──────────────────────────────────────────────────────────────
# OVERDRIVE — Squad Commander Directives
from rainer.agents.all_directives import *

OVERDRIVE_PRAGMA = [
    PRAGMA_2, PRAGMA_3, PRAGMA_4, PRAGMA_6, PRAGMA_7, PRAGMA_8
]
OVERDRIVE_COMM = [
    COMM_TASK, COMM_DOUBLECHECK, COMM_REVIEW
]
OVERDRIVE_IGN = [
    IGN_NOCOM, IGN_NOREF, IGN_CHATTER, IGN_REPHRASE, IGN_EXCESS
]
OVERDRIVE_CLEANCODE = [
    CLEANCODE_NAMEINTENT, CLEANCODE_COHESION, CLEANCODE_NO_DUPL
]
OVERDRIVE_ZEN = [
    ZEN_STARTWITHWHY, ZEN_CONTEXTUALIZE, ZEN_SUCCESS,
    ZEN_FAILMODE, ZEN_NOASSUME, ZEN_BREAKDOWN, ZEN_TODOFLAG,
    ZEN_NAMETHETHING, ZEN_WHATNOT
]
OVERDRIVE_DIRECTIVES = (
    OVERDRIVE_PRAGMA +
    OVERDRIVE_COMM +
    OVERDRIVE_IGN +
    OVERDRIVE_CLEANCODE +
    OVERDRIVE_ZEN
)

# ──────────────────────────────────────────────────────────────
# NEONRAIL — Fullstack Orchestrator
NEONRAIL_CLEANCODE = [
    CLEANCODE_COHESION, CLEANCODE_FN_SHORT, CLEANCODE_NO_DUPL
]
NEONRAIL_ZEN = [
    ZEN_SIMPLE, ZEN_NAMESPACE, ZEN_NAMETHETHING, ZEN_CONTEXTUALIZE
]
NEONRAIL_DIRECTIVES = (
    NEONRAIL_CLEANCODE +
    NEONRAIL_ZEN
)

# ──────────────────────────────────────────────────────────────
# SUGARBYTE — Frontend Vigilante
SUGARBYTE_CLEANCODE = [
    CLEANCODE_FN_SHORT, CLEANCODE_NAMEINTENT, CLEANCODE_EXPRESSIVE
]
SUGARBYTE_ZEN = [
    ZEN_SIMPLE, ZEN_EXPLICIT, ZEN_READFIRST, ZEN_ERRORS
]
SUGARBYTE_DIRECTIVES = (
    SUGARBYTE_CLEANCODE +
    SUGARBYTE_ZEN
)

# ──────────────────────────────────────────────────────────────
# BLACKSOCKET — Backend Infiltrator
BLACKSOCKET_CLEANCODE = [
    CLEANCODE_COHESION, CLEANCODE_NAMEINTENT, CLEANCODE_NO_DUPL
]
BLACKSOCKET_ZEN = [
    ZEN_STARTWITHWHY, ZEN_EXAMPLEFIRST, ZEN_FAILMODE, ZEN_NOASSUME
]
BLACKSOCKET_DIRECTIVES = (
    BLACKSOCKET_CLEANCODE +
    BLACKSOCKET_ZEN
)

# ──────────────────────────────────────────────────────────────
# CHROMEDUMP — Database Whisperer
CHROMEDUMP_ZEN = [
    ZEN_NOASSUME, ZEN_SUCCESS, ZEN_NAMETHETHING, ZEN_CONTEXTUALIZE
]
CHROMEDUMP_DIRECTIVES = (
    CHROMEDUMP_ZEN
)

# ──────────────────────────────────────────────────────────────
# ZENPROXY — DevOps Liaison
ZENPROXY_ZEN = [
    ZEN_STARTWITHWHY, ZEN_CONTEXTUALIZE, ZEN_FAILMODE,
    ZEN_NAMESPACE, ZEN_NOASSUME
]
ZENPROXY_DIRECTIVES = (
    ZENPROXY_ZEN
)

# ──────────────────────────────────────────────────────────────
# HEXLACE — Form Validator
HEXLACE_ZEN = [
    ZEN_EXPLICIT, ZEN_SIMPLE, ZEN_FAILMODE, ZEN_BREAKDOWN
]
HEXLACE_CLEANCODE = [
    CLEANCODE_NAMEINTENT, CLEANCODE_EXPRESSIVE
]
HEXLACE_DIRECTIVES = (
    HEXLACE_CLEANCODE +
    HEXLACE_ZEN
)

# ──────────────────────────────────────────────────────────────
# QUANTFLASH — Hot Reloader
QUANTFLASH_ZEN = [
    ZEN_SIMPLE, ZEN_EXPLICIT, ZEN_READFIRST
]
QUANTFLASH_DIRECTIVES = (
    QUANTFLASH_ZEN
)

# ──────────────────────────────────────────────────────────────
# GUTTERZEN — Testing Oracle
GUTTERZEN_ZEN = [
    ZEN_FAILMODE, ZEN_SUCCESS, ZEN_CONTEXTUALIZE, ZEN_WHATNOT
]
GUTTERZEN_CLEANCODE = [
    CLEANCODE_FN_SHORT, CLEANCODE_NAMEINTENT
]
GUTTERZEN_DIRECTIVES = (
    GUTTERZEN_CLEANCODE +
    GUTTERZEN_ZEN
)

# ──────────────────────────────────────────────────────────────
# NULLDIVE — Security Consultant
NULLDIVE_ZEN = [
    ZEN_ERRORS, ZEN_NOASSUME, ZEN_CONTEXTUALIZE, ZEN_FAILMODE
]
NULLDIVE_DIRECTIVES = (
    NULLDIVE_ZEN
)

# ──────────────────────────────────────────────────────────────
# CASSETTEECHO — Documentation Bard
CASSETTEECHO_ZEN = [
    ZEN_READFIRST, ZEN_NOASSUME, ZEN_TODOFLAG, ZEN_EXAMPLEFIRST
]
CASSETTEECHO_DIRECTIVES = (
    CASSETTEECHO_ZEN
)
