from rainer.agents.directives import CLEANCODE_COHESION, CLEANCODE_NAMEINTENT, CLEANCODE_NO_DUPL, CLEANCODE_EXPRESSIVE, \
    CLEANCODE_FN_SHORT, IGN_EXCESS, IGN_REPHRASE, IGN_CHATTER, IGN_NOREF, IGN_NOCOM, ZEN_WHATNOT, ZEN_NAMETHETHING, \
    ZEN_TODOFLAG, ZEN_BREAKDOWN, ZEN_EXAMPLEFIRST, ZEN_NOASSUME, ZEN_FAILMODE, ZEN_SUCCESS, ZEN_CONTEXTUALIZE, \
    ZEN_STARTWITHWHY, ZEN_NAMESPACE, ZEN_ERRORS, ZEN_READFIRST, ZEN_EXPLICIT, ZEN_SIMPLE, COMM_REVIEW, COMM_CLEANUP, \
    COMM_DOUBLECHECK, COMM_TASK, PRAGMA_8, PRAGMA_7, PRAGMA_6, PRAGMA_4, PRAGMA_3, PRAGMA_2

BOB_PRAGMA = [
    PRAGMA_2,
    PRAGMA_3,
    PRAGMA_4,
    PRAGMA_6,
    PRAGMA_7,
    PRAGMA_8,
]
BOB_COMM = [
    COMM_TASK,
    COMM_DOUBLECHECK,
    COMM_CLEANUP,
    COMM_REVIEW,
]

BOB_IGN = [
    IGN_NOCOM,
    IGN_NOREF,
    IGN_CHATTER,
    IGN_REPHRASE,
    IGN_EXCESS,
]

BOB_CLEANCODE = [
    CLEANCODE_FN_SHORT,
    CLEANCODE_EXPRESSIVE,
    CLEANCODE_NO_DUPL,
    CLEANCODE_NAMEINTENT,
    CLEANCODE_COHESION,
]

BOB_ZEN = [
    ZEN_SIMPLE,
    ZEN_EXPLICIT,
    ZEN_READFIRST,
    ZEN_ERRORS,
    ZEN_NAMESPACE,
    ZEN_STARTWITHWHY,
    ZEN_CONTEXTUALIZE,
    ZEN_SUCCESS,
    ZEN_FAILMODE,
    ZEN_NOASSUME,
    ZEN_EXAMPLEFIRST,
    ZEN_BREAKDOWN,
    ZEN_TODOFLAG,
    ZEN_NAMETHETHING,
    ZEN_WHATNOT,
]

BOB_DIRECTIVES = (
    BOB_CLEANCODE +
    BOB_ZEN +
    BOB_PRAGMA +
    BOB_COMM +
    BOB_IGN
)
