# Generated by Django 5.1.6 on 2025-03-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codegenerationdata',
            name='rainer_file',
        ),
        migrations.AddField(
            model_name='codegenerationdata',
            name='rainer_branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='codegenerationdata',
            name='rainer_path',
            field=models.CharField(default='', max_length=255),
        ),
    ]
