# Generated by Django 5.1.7 on 2025-03-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainer', '0008_alter_codegenerationdata_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codegenerationdata',
            old_name='rainer_branch',
            new_name='rainer_project',
        ),
    ]
