# Generated by Django 5.1.7 on 2025-03-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rainer', '0009_rename_rainer_branch_codegenerationdata_rainer_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codegenerationdata',
            options={'ordering': ('-created_at', 'rainer_project', 'rainer_path', 'llm_model')},
        ),
    ]
